CREATE TABLE tb_persons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   nome VARCHAR(255) NOT NULL,
   cpf BIGINT NOT NULL,
   excluido BOOLEAN NOT NULL,
   endereco VARCHAR(255),
   cep INTEGER NOT NULL,
   cidade VARCHAR(255),
   medico BOOLEAN NOT NULL,
   crm VARCHAR(255),
   CONSTRAINT pk_tb_persons PRIMARY KEY (id)
);

ALTER TABLE tb_persons ADD CONSTRAINT uc_tb_persons_cpf UNIQUE (cpf);


CREATE TABLE tb_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   hour_event INTEGER,
   day_event date,
   patient_id BIGINT,
   medic_id BIGINT,
   CONSTRAINT pk_tb_events PRIMARY KEY (id)
);

ALTER TABLE tb_events ADD CONSTRAINT FK_TB_EVENTS_ON_MEDIC FOREIGN KEY (medic_id) REFERENCES tb_persons (id);

ALTER TABLE tb_events ADD CONSTRAINT FK_TB_EVENTS_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES tb_persons (id);